networks:
  locally:

services:
  rest:
    build:
      context: ../aspnet
      dockerfile: ../.docker/machine.dockerfile
    depends_on:
      - data
    environment:
      ConnectionStrings__pgsql: 'Host=data;Database=AccountData;Username=postgres;Password=LocalState@2021;'
    networks:
      - locally
    ports:
      - 8000:80

  data:
    environment:
      POSTGRES_PASSWORD: LocalState@2021
    image: postgres:13-alpine
    networks:
      - locally
    volumes:
      - accountstore:/var/lib/postgresql/data
    ports:
      - 5432:5432

version: '3.8'

volumes:
  accountstore:
